# Generated by Django 4.0.4 on 2022-06-08 19:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemedicine', '0006_alter_doctor_hospital_affliations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(null=True)),
                ('p_address', models.CharField(blank=True, max_length=100, null=True)),
                ('landline', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('curr_med', models.CharField(blank=True, max_length=100, null=True)),
                ('temp', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('pres_prob', models.CharField(blank=True, max_length=100, null=True)),
                ('assessments', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('nxt_cons_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telemedicine.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telemedicine.patient')),
            ],
        ),
    ]
