# Generated by Django 4.0.4 on 2022-06-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0002_alter_consultationrecord_consultation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrecord',
            name='nxt_cons_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
