# Generated by Django 4.0.4 on 2022-06-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0003_alter_consultationrecord_nxt_cons_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
