# Generated by Django 4.0.4 on 2022-06-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0003_alter_consultationrecord_nxt_cons_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='docus/'),
        ),
    ]
