# Generated by Django 4.0.4 on 2022-06-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0004_consultationrecord_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrecord',
            name='documents',
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='docus/')),
                ('cons_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_record.consultationrecord')),
            ],
        ),
    ]
