# Generated by Django 4.0.4 on 2022-06-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0004_consultationrecord_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrecord',
            name='link',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_record.consultationrecord')),
            ],
        ),
    ]
