# Generated by Django 4.0.4 on 2022-06-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0005_remove_consultationrecord_documents_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='docus/'),
        ),
    ]
