# Generated by Django 4.0.4 on 2022-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0005_remove_consultationrecord_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
