# Generated by Django 4.0.4 on 2022-06-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0006_consultationrecord_document'),
        ('consultation_record', '0006_consultationrecord_link_delete_link'),
    ]

    operations = [
    ]
