# Generated by Django 4.0.4 on 2022-06-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_record', '0007_merge_20220609_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='prescriptions',
            field=models.FileField(blank=True, null=True, upload_to='docus/'),
        ),
    ]
