# Generated by Django 4.0.4 on 2022-06-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='attending_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docpatient', to='telemedicine.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='docus/'),
        ),
    ]
