# Generated by Django 4.0.4 on 2022-06-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0004_doctor_age_doctor_birthdate_doctor_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_affliations',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
